#!/usr/bin/env python3

import numpy as np
import matplotlib.pyplot as plt

# Load data from text file
error_data = np.loadtxt('/tmp/error.txt')



# Plotting
plt.figure(figsize=(12, 8))

# Plot error
plt.plot(error_data[:, 0], error_data[:, 1], label='Error', linestyle='--')

# Plot setpoint
plt.plot(error_data[:, 0], error_data[:, 2], label='Setpoint')

plt.xlabel('Iteration')
plt.ylabel('Value')
plt.title('Error vs Iteracion')
plt.legend()
plt.grid(True)

plt.show()

