#!/usr/bin/env python3
import numpy as np
import matplotlib.pyplot as plt

# Load data from text files
desired_output = np.loadtxt('/tmp/qdeseado.txt')
current_output = np.loadtxt('/tmp/qactual.txt')


# Plot desired output
plt.plot(desired_output[:, 0], desired_output[:, 1], label='Desired q1')
plt.plot(desired_output[:, 0], desired_output[:, 2], label='Desired q2')
plt.plot(desired_output[:, 0], desired_output[:, 3], label='Desired q3')
plt.plot(desired_output[:, 0], desired_output[:, 4], label='Desired q4')
plt.plot(desired_output[:, 0], desired_output[:, 5], label='Desired q5')
plt.plot(desired_output[:, 0], desired_output[:, 6], label='Desired q6')
plt.plot(desired_output[:, 0], desired_output[:, 7], label='Desired q7')

# Plot current output
plt.plot(current_output[:, 0], current_output[:, 1], label='current q1', linestyle='--')
plt.plot(current_output[:, 0], current_output[:, 2], label='current q2', linestyle='--')
plt.plot(current_output[:, 0], current_output[:, 3], label='current q3', linestyle='--')
plt.plot(current_output[:, 0], current_output[:, 4], label='current q4', linestyle='--')
plt.plot(current_output[:, 0], current_output[:, 5], label='current q5', linestyle='--')
plt.plot(current_output[:, 0], current_output[:, 6], label='current q6', linestyle='--')
plt.plot(current_output[:, 0], current_output[:, 7], label='current q7', linestyle='--')


plt.xlabel('Time')
plt.ylabel('Position')
plt.title('Position vs Time')
plt.legend()
plt.grid(True)

plt.show()

