#!/usr/bin/env python3

import rospy
from sensor_msgs.msg import JointState
from markers import *
from proy_functions import *

if __name__ == '__main__':

    rospy.init_node("testInvKineGrad")
    pub = rospy.Publisher('joint_states', JointState, queue_size=1)

    bmarker      = BallMarker(color['RED'])
    bmarker_des  = BallMarker(color['GREEN'])

    # Joint names
    jnames = ['rev1', 'rev2', 'rev3','rev4', 'rev5', 'rev6','slider9','slider10']

    # Desired position
    xd = np.array([0.74, 0.225, 0.449])
    # Initial configuration
    #q0 = np.array([0.0, -1.0, 1.7, -2.2, -1.6, 0.0])
    q0 = np.array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5])
    # Inverse kinematics
    q = ik_gradient_mh5lsii(xd, q0)

    # Resulting position (end effector with respect to the base link)
    T = fkine_mh5lsii(q)
    print('Obtained value:\n', np.round(T,3))

    # Red marker shows the achieved position
    bmarker.xyz(T[0:3,3])
    # Green marker shows the desired position
    bmarker_des.xyz(xd)

    # Objeto (mensaje) de tipo JointState
    jstate = JointState()
    # Asignar valores al mensaje
    jstate.header.stamp = rospy.Time.now()
    jstate.name = jnames
    # Add the head joint value (with value 0) to the joints
    jstate.position = np.append(q, [0, 0])

    # Loop rate (in Hz)
    rate = rospy.Rate(100)
    
    # Continuous execution loop
    while not rospy.is_shutdown():
        # Current time (needed for ROS)
        jstate.header.stamp = rospy.Time.now()
        # Publish the message
        pub.publish(jstate)
        bmarker.publish()
        bmarker_des.publish()
        # Wait for the next iteration
        rate.sleep()
